### ISSUE TITLE
Package repr 0.2

### ISSUE THREAD

**Issue by takluyver** [IRkernel/irkernel.github.io#12]
I've pushed a 0.2 tag to the repr repo.

Ping @JanSchulz for packaging. I've also invited you to be a collaborator - I still like us all to work through pull requests for non-trivial changes, but you've definitely done enough to get commit rights. And it would be handy to be able to assign issues like this one to you! :-)

**Comment by jankatins** [comment]
Ok, I followed the invitations and am now listed as a contributor to the IRkernel org. Thanks for inviting me!

Just for the record: I can only do the (windows) packaging stuff, for more I'm not a good enough R dev :-( 

I will still work through PRs ans let one of you merge them into the repo.

**Comment by takluyver** [comment]
Great, thanks! I'm not a very good R dev either, so don't assume the packaging is the only thing you can work on. But that in itself is very valuable - it's no good writing software if we can't give it to other people.

**Comment by flying-sheep** [comment]
i don’t think R is hard to learn even at a deeper level of understanding.

i superficially learned R for my master’s thesis 1½ years ago, and only did more in it when i started my PhD ½ year ago. still i think i got most of it nailed down. syntax, lazy evaluation, 3 class systems, conventions, package structure & ecosystem, …

---

this bug is fixed, i presume?
